# Generated by Django 4.0.4 on 2022-05-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='uri',
            field=models.URLField(default='d544b1aada4f4ce'),
        ),
    ]
